export const TALLERES_TYPES = {
  OBTENER_LISTA_TALLERES_START: "[TALLERES] OBTENER_LISTA_TALLERES_START",
  OBTENER_LISTA_TALLERES_FAILED: "[TALLERES] OBTENER_LISTA_TALLERES_FAILED",
  OBTENER_LISTA_TALLERES_FINISH: "[TALLERES] OBTENER_LISTA_TALLERES_FINISH",
  ADD_TO_FAVORITE: "[TALLERES] ADD_TO_FAVORITE",
  REMOVE_FROM_FAVORITE: "[TALLERES] REMOVE_FROM_FAVORITE",
};
