export const RINCONES_TYPES = {
  OBTENER_LISTA_RINCONES_START: "[rincones] OBTENER_LISTA_RINCONES_START",
  OBTENER_LISTA_RINCONES_FINISH: "[rincones] OBTENER_LISTA_RINCONES_FINISH",
  OBTENER_LISTA_RINCONES_FAILED: "[rincones] OBTENER_LISTA_RINCONES_FAILED",
  ADD_TO_FAVORITE: "[rincones] ADD_TO_FAVORITE",
  REMOVE_FROM_FAVORITE: "[rincones] REMOVE_FROM_FAVORITE",
};
