export const ACTION_TYPES = {
  OBTENER_LISTA_TALLERES_START: "OBTENER_LISTA_TALLERES_START",
  OBTENER_LISTA_TALLERES_FINISH: "OBTENER_LISTA_TALLERES_FINISH",
  OBTENER_LISTA_TALLERES_FAILED: "OBTENER_LISTA_TALLERES_FAILED",
  OBTENER_LISTA_RINCONES_START: "OBTENER_LISTA_RINCONES_START",
  OBTENER_LISTA_RINCONES_FINISH: "OBTENER_LISTA_RINCONES_FINISH",
  OBTENER_LISTA_RINCONES_FAILED: "OBTENER_LISTA_RINCONES_FAILED",
  ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
  REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE",
};
